name: Docker
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * *'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build
        run: |
          echo "${{secrets.DOCKER_TOKEN}}" | docker login -u starudream --password-stdin
          docker build -t starudream/cronjob:latest .
          docker push starudream/cronjob:latest
