name: Docker
on:
  - push
env:
  USERNAME: starudream
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: bash build.sh cronjob
